config/routes.rb
Djsync::Application.routes.draw do

  match 'songs/:id/vote_up' => 'songs#vote_up'

  match 'parties/new/upload' => 'parties#upload'
  match 'parties/:id/library' => 'parties#library'
  match 'parties/:id/player' => 'parties#player'

  match 'songs/:id/reset' => 'songs#reset'

  resources :songs

  resources :parties

  resources :users

  root :to => 'home#index'

end

app/models/party.rb
class Party < ActiveRecord::Base
  attr_accessible :id, :start_date, :end_date, :url, :party_name, :party_location, :party_type, :party_details
  attr_accessible :playlist

  has_many :songs, :dependent => :destroy
  has_many :users

  def playlist=(uploaded_io)
    file = File.open(Rails.root.join(uploaded_io.original_filename), 'w')
    file.write(uploaded_io.read)
    raw = uploaded_io.original_filename
    file.close
    reformat raw
  end

  def reformat(raw)
  file = File.open(raw, 'r:UTF-8')
  newFile = File.open(Rails.root.join(raw + ".new"), 'w')


  file.each do |line|

#
#  Just for debugging.
#  print "Reading " + line
#

# Capturing two patterns here:
#  <key>XXXX</key><string>YYYY</string>
#  <key>XXXX</key><integer>ZZZZ</integer>
#
      if line =~ /(\s+)<key>([a-zA-Z ]+)<\/key><(string|integer)>([^<]+)<\/(string|integer)>/
        space = $1
        value = $4
        tag = $2.gsub(' ', '_')
        newFile.write space + "<#{tag}>"  + value.to_s  + "</#{tag}>\n"
        #
        # Capturing two patterns here:
        #  <key>XXXX</key><true/>
        #  <key>XXXX</key><false/>
        #
      elsif line =~ /(\s+)<key>([a-zA-Z ]+)<\/key><(true|false)\/>/
        space = $1
        value = $3
        tag = $2.gsub(' ', '_')
        newFile.write space + "<#{tag}>"  + value.to_s  + "</#{tag}>\n"
        #
        # Everything else is not tranlsated
        #
      else
        newFile.write line
      end

  end
  newFile.close
  import newFile
  end

  def import (newFile)
    require 'rexml/document'
    file = File.open(newFile, 'r:UTF-8')
    xml = file.read

    doc = REXML::Document.new(xml)

    count = 0
    doc.elements.each("plist/dict/dict/dict") do |dict|

      #
      # create a Track object for each "dict"
      #
      song = Song.new

      if dict.elements['Name']
        song.song_name= dict.elements['Name'].text
      end

      if dict.elements['Artist']
        song.song_artist = dict.elements['Artist'].text
      end

      if dict.elements['Album']
        song.song_album = dict.elements['Album'].text
      end

      if dict.elements['Total_Time']
        song.song_duration = dict.elements['Total_Time'].text
      end

      if dict.elements['Location']
        song.song_location = dict.elements['Location'].text
      end

      count += 1
      song.party_id = id
      song.save
    end

  end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  # GET /parties
  # GET /parties.json

  def upload
    uploaded_io = params[:party][:playlist]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])
    session[:score]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  def library
    @party = Party.find(params[:id])
    session[:score]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  def player
    @party = Party.find(params[:id])
    session[:score]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.json



  def create

    @party = Party.create
    @party.update_attributes(params[:party])


    i = (rand * 1000000).round

    while (Party.find_by_identifier(i))
      i = (rand * 1000000).round
    end

    @party.identifier =  i


    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
  <%= form_for(@party, multipart: true) do |f| %>
    <% if @party.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

        <ul>
        <% @party.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label>
        What is your party name?
      </label>
      <%= f.text_field :party_name %>
    </div>


    <div class="field">
      <label>
        What type of party is it?
      </label>
      <%= f.text_field :party_type %>
    </div>

    <div class="field">
      <label>
        Where are you partying?
      </label>
      <%= f.text_field :party_location %>
    </div>

    <div class="field">
      <label>
        When does your party begin?
      </label>
      <div class="select"><%= f.datetime_select :start_date, :ampm => true, :start_year => 2013, :start_minute => 0, :order => [:month, :day, :year] %></div>
    </div>

    <div class="field">
      <label>
        When does your party end?
      </label>
      <div class="select"><%= f.datetime_select :end_date, :ampm => true, :order => [:month, :day, :year] %></div>
    </div>

    <div class="field">
      <label>
        Any additional details?
      </label>
      <%= f.text_area :party_details %>
    </div>

    <div class="field">
      <label>
        Upload your Playlist!
      </label>
        <%= f.file_field :playlist %>
    </div>

    <div class="actions cf">
      <%= f.submit %>
    </div>

    <div class="clear"></div> 
  <% end %>

app/views/parties/edit.html.erb
<h1 class="form_titles">Editing party</h1>

<%= render 'form' %>

<div style="text-align:center;">
	<%= link_to 'Show', @party %> |
	<%= link_to 'Back', parties_path %>
</div>

app/views/parties/index.html.erb
<h1>Current Parties</h1>
<h3>Administrators Only</h3>

<table>
  <tr>
    <th>Party ID</th>
    <th>Party</th>
    <th>Identifier</th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td><%= party.id %></td>
    <td><%= party.party_name %></td>
    <td><%= party.identifier %></td>
    <td><%= link_to 'Show', party %></td>
    <td><%= link_to 'Edit', edit_party_path(party) %></td>
    <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Party', new_party_path %>

app/views/parties/library.html.erb
<div id="nav_container">
  <nav id="nav">
    <ul class="cf">
      <li>DJ<span>SYNC</span></li>
      <li><a href="/parties/<%=@party.id%>/">Setlist</a></li>
      <li><a href="/parties/<%=@party.id%>/library">Library</a></li>
      <li><a href="">Party</a>
        <div>
          <ul>
            <li><a href="">Join Party</a></li>
            <li><a href="">Create Party</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </nav>
</div>

<div id="contentdiv">
  <p id="notice"><%= notice %></p>
  <div class="party_header">
      <h1><%= @party.party_name %>  <span class="button">View Party Details</span></h1>
      <div class="party_description">
        <h2 class="cf"><span>Party Type:</span><%= @party.party_type %></h2>
        <h2 class="cf"><span>Party Location:</span><%= @party.party_location %></h2>
        <h2 class="cf"><span>Party Time:</span><%= @party.start_date.strftime("%B %d, %Y at %I:%M%p") %></h2>
        <h2 class="cf"><span>Party Identifier:</span><%= @party.identifier %></h2>
        <p>Party Details</p>
        <%= @party.party_details %>
      </div>   
  </div>



  <div class="playlist">
    <h2><%= @party.party_name %> Library:</h2>

      <% if @party.songs.empty? %>
          No songs have been added to this party's playlist.
      <% else %>
        <div>
          <ul class="playlist_container">
          <% @party.songs.select{|s| s.score == 0}.sort!{|f1,f2|f2.score.to_i <=> f1.score.to_i}.each do |f| %>
              <li class="playlist_row cf"> 
                <p><%= f.song_name %></p>
                <p><%= f.song_artist %></p>


                <p>
                  <% if !session[:votes].include? f.id %>
                    <%= link_to 'Add to Setlist!', :controller => 'songs', :action => 'vote_up', :id => f.id %>
                  <% else %>
                    Already played.
                  <% end %>
                </p>

              </li>
          <% end %>
        </ul> 
    <% end %>
    </div>
    </p>
  </div>

  <div style="text-align:center;">
    <%= link_to 'Back to Setlist', :controller => 'parties', :action => 'show'%>

  </div>
</div> 

app/views/parties/new.html.erb
<div id="contentdiv">
	<h1 class="form_titles">Create a Party</h1>

	<%= render 'form' %>

	<div style="text-align:center;">
		<%= link_to 'Back', parties_path %>
	</div>
</div> 
<style type="text/css"> 
	#nav_container{
		display: none;
	}

	#contentdiv{
		padding-top: 30px;
		padding-bottom: 30px;
	}

</style>

app/views/parties/player.html.erb
<div id="nav_container">
  <nav id="nav">
    <ul class="cf">
      <li>DJ<span>SYNC</span></li>
      <li><a href="/parties/<%=@party.id%>/">Setlist</a></li>
      <li><a href="/parties/<%=@party.id%>/library">Library</a></li>
      <li><a href="">Party</a>
        <div>
          <ul>
            <li><a href="">Join Party</a></li>
            <li><a href="">Create Party</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </nav>
</div>

<div id="contentdiv">
  <div id="notice"><%= notice %></div>
  <div class="party_header">
    <h1><%= @party.party_name %>  <span class="button">View Party Details</span></h1>
    <div class="party_description">
      <h2 class="cf"><span>Party Type:</span><%= @party.party_type %></h2>
      <h2 class="cf"><span>Party Location:</span><%= @party.party_location %></h2>
      <h2 class="cf"><span>Party Time:</span><%= @party.start_date.strftime("%B %d, %Y at %I:%M%p") %></h2>
      <h2 class="cf"><span>Party Identifier:</span><%= @party.identifier %></h2>
      <p>Party Details</p>
      <%= @party.party_details %>
    </div>
  </div>


<div class="player">

<% playlist = @party.songs.select{|s| s.score > 0}.sort!{|f1,f2|f2.score.to_i <=> f1.score.to_i} %>

Now Playing: <%= playlist.first.song_name %> by <%= playlist.first.song_artist %> <br/><br/>

<audio controls autoplay>
  <source src="<%= playlist.first.song_location %>" type="audio/mpeg">
</audio>

  <%= link_to 'Play Next Song', :controller => 'songs', :action => 'reset', :id => playlist.first.id %>

</div>

</div>

app/views/parties/show.html.erb
<div id="nav_container">
  <nav id="nav">
    <ul class="cf">
      <li>DJ<span>SYNC</span></li>
      <li><a href="/parties/<%=@party.id%>/">Setlist</a></li>
      <li><a href="/parties/<%=@party.id%>/library">Library</a></li>
      <li><a href="">Party</a>
        <div>
          <ul>
            <li><a href="">Join Party</a></li>
            <li><a href="">Create Party</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </nav>
</div>



<div id="contentdiv">
  <% if flash[:notice] %>
      <div id="notice">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <br/>
  <div class="party_header">
      <h1><%= @party.party_name %>  <span class="button">View Party Details</span></h1>
      <div class="party_description">
        <h2 class="cf"><span>Party Type:</span><%= @party.party_type %></h2>
        <h2 class="cf"><span>Party Location:</span><%= @party.party_location %></h2>
        <h2 class="cf"><span>Party Time:</span><%= @party.start_date.strftime("%B %d, %Y at %I:%M%p") %></h2>
        <h2 class="cf"><span>Party Identifier:</span><%= @party.identifier %></h2>
        <p>Party Details</p>
        <%= @party.party_details %>
      </div>   
  </div>



  <div class="playlist">
    <h2><%= @party.party_name %> Setlist:</h2>

      <% if @party.songs.empty? %>
          No songs have been added to this party's playlist.
      <% else %>
        <div>
          <ul class="playlist_container">
          <% @party.songs.select{|s| s.score > 0}.sort!{|f1,f2|f2.score.to_i <=> f1.score.to_i}.each do |f| %>
              <li class="playlist_row cf"> 
                <p><%= f.song_name %></p>
                <p><%= f.song_artist %></p>
                <p><%= f.score %> Votes</p>

                <p>
                  <% if !session[:votes].include? f.id %>
                    <%= link_to 'Vote up!', :controller => 'songs', :action => 'vote_up', :id => f.id %>
                  <% else %>
                    Voted up!
                  <% end %>
                </p>

              </li>
          <% end %>
        </ul> 
    <% end %>
    </div>
    </p>
  </div>

  <div style="text-align:center;">
    <%= link_to 'Add a Song!', :controller => 'parties', :action => 'library'%> |
    <%= link_to 'Edit', edit_party_path(@party) %> |
    <%= link_to 'Back', parties_path %>
  </div>
</div> 