config/routes.rb
Djsync::Application.routes.draw do

  match 'songs/:id/vote_up' => 'songs#vote_up'

  match 'parties/new/upload' => 'parties#upload'
  match 'parties/:id/library' => 'parties#library'
  match 'parties/:id/player' => 'parties#player'

  match 'songs/:id/reset' => 'songs#reset'

  resources :songs

  resources :parties

  resources :users

  root :to => 'home#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :song_album, :song_artist, :song_duration, :song_location, :song_name, :party_id, :score
  belongs_to :party, :dependent => :destroy
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json

  def reformat
    file = File.open('3.xml', 'r:UTF-8')

    file.each do |line|

#
#  Just for debugging.
#  print "Reading " + line
#

# Capturing two patterns here:
#  <key>XXXX</key><string>YYYY</string>
#  <key>XXXX</key><integer>ZZZZ</integer>
#
      if line =~ /(\s+)<key>([a-zA-Z ]+)<\/key><(string|integer)>([^<]+)<\/(string|integer)>/
        space = $1
        value = $4
        tag = $2.gsub(' ', '_')
        print space + "<#{tag}>"  + value.to_s  + "</#{tag}>\n"
        #
        # Capturing two patterns here:
        #  <key>XXXX</key><true/>
        #  <key>XXXX</key><false/>
        #
      elsif line =~ /(\s+)<key>([a-zA-Z ]+)<\/key><(true|false)\/>/
        space = $1
        value = $3
        tag = $2.gsub(' ', '_')
        print space + "<#{tag}>"  + value.to_s  + "</#{tag}>\n"
        #
        # Everything else is not tranlsated
        #
      else
        print line
      end
    end
  end

  def reset
    @song = Song.find(params[:id])
    @song.update_attribute(:score, @song.score = 0)
    @song.save

    redirect_to :back
  end

  def vote_up
    @song  = Song.find(params[:id])

    if !session[:votes].include? @song.id
      session[:votes].push @song.id
      @song.score = @song.score + 1
      @song.save
    end

    redirect_to :back
  end

  def index
    @songs = Song.all
    @songs.sort!{|s1,s2|s2.score.to_i <=> s1.score.to_i}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new
    # @song.party_id = @party.find(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :party_id %><br />
    <%= f.text_field :party_id %>
  </div>
  <div class="field">
    <%= f.label :song_name %><br />
    <%= f.text_field :song_name %>
  </div>
  <div class="field">
    <%= f.label :song_artist %><br />
    <%= f.text_field :song_artist %>
  </div>
  <div class="field">
    <%= f.label :song_album %><br />
    <%= f.text_field :song_album %>
  </div>
  <div class="field">
    <%= f.label :song_duration %><br />
    <%= f.time_select :song_duration %>
  </div>
  <div class="field">
    <%= f.label :song_location %><br />
    <%= f.text_field :song_location %>
  </div>

    <%= link_to 'Reset Votes', {:controller => 'songs', :action => 'reset'} %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1 class="form_titles">Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Party</th>
    <th>Song name</th>
    <th>Song artist</th>
    <th>Song album</th>
    <th>Song duration</th>
    <th>Song location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.party_id %></td>
    <td><%= song.song_name %></td>
    <td><%= song.song_artist %></td>
    <td><%= song.song_album %></td>
    <td><%= song.song_duration %></td>
    <td><%= song.song_location %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Party ID:</b>
  <%= @song.party_id %>
</p>

<p>
  <b>Song name:</b>
  <%= @song.song_name %>
</p>

<p>
  <b>Song artist:</b>
  <%= @song.song_artist %>
</p>

<p>
  <b>Song album:</b>
  <%= @song.song_album %>
</p>

<p>
  <b>Song duration:</b>
  <%= @song.song_duration %>
</p>

<p>
  <b>Song location:</b>
  <%= @song.song_location %>
</p>

<br />


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>